backend:
  name: github
  repo: PopJoker/pop-blog
  branch: main
  base_url: https://decap-cms-oauth.vercel.app
  auth_endpoint: auth

media_folder: 'public/static/images'
public_folder: 'public/static/images'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'data/blog'
    create: true
    slug: '{{fields.slug}}'
    extension: mdx
    format: frontmatter

    fields:
      - { label: '標題', name: 'title', widget: 'string' }

      - { label: '網址 Slug', name: 'slug', widget: 'string' }

      - { label: '發布日期', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD' }

      - { label: '摘要', name: 'summary', widget: 'text' }

      - { label: '封面圖', name: 'cover', widget: 'image', required: false }

      - { label: '標籤', name: 'tags', widget: 'list' }

      - {  label: '作者', name: 'authors', widget: 'list' ,default: ['default'] }

      - { label: '是否草稿', name: 'draft', widget: 'boolean', default: false }

      - { label: '內容', name: 'body', widget: 'markdown' }
