backend:
  name: git-gateway
  repo: popjoker/pop-blog
  branch: main
  # 加上下面這一行，直接指定身份驗證的路徑
  identity_url: "https://remarkable-selkie-7decfb.netlify.app/.netlify/identity"
  gateway_url: "https://remarkable-selkie-7decfb.netlify.app/.netlify/git/github"

site_url: https://popjoker.github.io/pop-blog

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }